name: An example of shared workflow

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-lates
    steps:
      - run: echo "Testing!"
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Building!"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploying!"

  
