name: An example of shared workflow

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"
